---
title: "Proyecto"
author: "Mariana Godina Abasolo 113682 
Akira Hirata Garcia 124547 
Cesar Jimenez 126346"
date: "Tuesday, October 28, 2014"
output: pdf_document
---
Cargar los datos y limpiarlos

```{r}
#datos por mes (femenino)
mesfem2003 <- read.csv("~/CVS/Mes/mesfem2003.csv", stringsAsFactors=FALSE)
mesfem2004 <- read.csv("~/CVS/Mes/mesfem2004.csv", stringsAsFactors=FALSE)
mesfem2005 <- read.csv("~/CVS/Mes/mesfem2005.csv", stringsAsFactors=FALSE)
mesfem2006 <- read.csv("~/CVS/Mes/mesfem2006.csv", stringsAsFactors=FALSE)
mesfem2007 <- read.csv("~/CVS/Mes/mesfem2007.csv", stringsAsFactors=FALSE)
mesfem2008 <- read.csv("~/CVS/Mes/mesfem2008.csv", stringsAsFactors=FALSE)
mesfem2009 <- read.csv("~/CVS/Mes/mesfem2009.csv", stringsAsFactors=FALSE)
mesfem2010 <- read.csv("~/CVS/Mes/mesfem2010.csv", stringsAsFactors=FALSE)
mesfem2011 <- read.csv("~/CVS/Mes/mesfem2011.csv", stringsAsFactors=FALSE)
mesfem2012 <- read.csv("~/CVS/Mes/mesfem2012.csv", stringsAsFactors=FALSE)
mesfem2013 <- read.csv("~/CVS/Mes/mesfem2013.csv", stringsAsFactors=FALSE)
```

You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
